### ISSUE TITLE
golang版本切换报错

### ISSUE THREAD

**Issue by soooldier** [weibreeze/breeze-go#4]
测试代码在这里：https://github.com/soooldier/golang-module-hash-test
测试步骤：
1. go1.12运行script/build.sh
2. 切换到go1.13
3. 删掉go.sum
4. 再执行script/build.sh报错

```shell
go: downloading github.com/weibreeze/breeze-go v0.1.0
verifying github.com/weibreeze/breeze-go@v0.1.0: checksum mismatch
	downloaded: h1:+++pO6wSn6jNsX6iNnSYjiQsSVPWGD4O/iA0yzGw7s8=
	go.sum:     h1:7uALKaS/Nxv2O2vSwrS0+3KybL58Y2rWyYaRKgl/YOw=
```

**Comment by rayzhang0603** [comment]
可以`go clean -modcache`清除mod缓存试试。

这里有类似[case](https://stackoverflow.com/questions/54133789/go-modules-checksum-mismatch)

**Comment by soooldier** [comment]
@rayzhang0603 感谢回复，清掉cache后肯定不会报错了，我只是不明白为啥会有同一个包针对两个不同的golang版本会出现hash值不一样的情况

**Comment by oGre222** [comment]
sum.golang.org 缓存commit hash异常，这里是否有修改过tag信息呢？

**Comment by rayzhang0603** [comment]
@oGre222 确实修改过tag。。
@soooldier 已经发布0.1.1版本，可以使用这个版本试试。

**Comment by oGre222** [comment]
> @oGre222 确实修改过tag。。
> @soooldier 已经发布0.1.1版本，可以使用这个版本试试。

明白，那就是这个问题导致sumcheck错误了。官方目前[不支持tag修改](https://github.com/golang/go/issues/37769#issuecomment-597156667)

**Comment by soooldier** [comment]
@rayzhang0603 收到，谢谢
